-- CREATE TABLE INFORMATION(
-- 	NUMBERS INT(5)
-- 	,FULLNAME VARCHAR(50) NOT NULL
-- 	,AGE INT(3) NOT NULL
-- 	,GENDER ENUM('F','M')
-- 	,SIGN_DATE DATETIME NOT NULL
-- 	,OUT_DATE DATETIME
-- 	,CONSTRAINT Pk_employess_NUMBERS PRIMARY KEY(NUMBERS)
-- );

-- ALTER TABLE information ADD COLUMN ADDR1 VARCHAR(300);

-- ALTER TABLE information ALTER COLUMN addr1 VARCHAR(200);

-- ALTER TABLE information drop COLUMN addr1;

-- SHOW FULL COLUMNS FROM information;

-- ALTER TABLE information ADD COLUMN addr1 VARCHAR(200);

-- INSERT INTO information(NUMBERS,FULLNAME,AGE,GENDER,SIGN_DATE,OUT_DATE,ADDR1)
-- VALUES (01,'김진아',30,'F',NOW(),NULL,NULL); 

-- SELECT * FROM information; 

-- COMMIT;

-- INSERT INTO information(NUMBERS,FULLNAME,AGE,GENDER,SIGN_DATE,OUT_DATE,ADDR1)
-- VALUES (04,'김진아',30,'F',NOW(),NULL,NULL);

-- DELETE FROM information
-- WHERE NUMBERS = 4;

-- TRUNCATE TABLE information;

-- DROP TABLE information;